resources:
- name: srkamineni_repo
  type: git
  source:
    branch: main
    #password: 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
    uri: https://github.com/srkamineni/concourse.git

jobs:
- name: hello-world-job
  plan:
  - get: srkamineni_repo
    trigger: true
  - task: hello-world-task
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: busybox
      run:
        path: echo
        args: ["Hello World SAP!"]
